[build]
builder = "NIXPACKS"
buildCommand = "npm ci && npm run build"

[deploy]
staticPublishPath = "dist"

[environments.production.variables]
NODE_ENV = "production"
VITE_API_URL = "${{BACKEND_URL}}"
VITE_APP_NAME = "HelpSavta"
VITE_APP_VERSION = "1.0.0"

[environments.staging.variables]
NODE_ENV = "staging"
VITE_API_URL = "${{BACKEND_URL}}"
VITE_APP_NAME = "HelpSavta"
VITE_APP_VERSION = "1.0.0"