# Nixpacks configuration for HelpSavta backend

[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = [
    "npm ci --only=production",
    "npx prisma generate"
]

[phases.build]
cmds = [
    "npm run build"
]

[phases.deploy]
cmds = [
    "npx prisma migrate deploy"
]

[start]
cmd = "node dist/server.js"

[variables]
NODE_ENV = "production"
PORT = "3001"