name: Deploy Infrastructure to Azure

on:
  push:
    branches: [main]
    paths:
      - 'azure/**'
      - '.github/workflows/deploy-infrastructure.yml'
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force deployment even if no changes detected'
        required: false
        default: false
        type: boolean

env:
  AZURE_RESOURCE_GROUP: helpsavta-prod-rg
  AZURE_LOCATION: westeurope
  BICEP_FILE: azure/simplified-main.bicep
  PARAMETERS_FILE: azure/simplified-parameters.json

jobs:
  validate-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Validate Bicep template
      run: |
        echo "Validating Bicep template..."
        az deployment group validate \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --template-file ${{ env.BICEP_FILE }} \
          --parameters @${{ env.PARAMETERS_FILE }} \
          --parameters postgresAdminPassword='${{ secrets.POSTGRES_ADMIN_PASSWORD }}'

    - name: Deploy infrastructure
      run: |
        echo "Deploying infrastructure..."
        az deployment group create \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --template-file ${{ env.BICEP_FILE }} \
          --parameters @${{ env.PARAMETERS_FILE }} \
          --parameters postgresAdminPassword='${{ secrets.POSTGRES_ADMIN_PASSWORD }}' \
          --mode Incremental \
          --verbose

    - name: Get deployment outputs
      id: outputs
      run: |
        echo "Getting deployment outputs..."
        BACKEND_URL=$(az deployment group show \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --name simplified-main \
          --query "properties.outputs.backendAppUrl.value" \
          --output tsv)
        
        FRONTEND_URL=$(az deployment group show \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --name simplified-main \
          --query "properties.outputs.staticWebAppUrl.value" \
          --output tsv)
        
        echo "BACKEND_URL=${BACKEND_URL}" >> $GITHUB_OUTPUT
        echo "FRONTEND_URL=${FRONTEND_URL}" >> $GITHUB_OUTPUT
        
        echo "Backend URL: ${BACKEND_URL}"
        echo "Frontend URL: ${FRONTEND_URL}"

    - name: Update deployment status
      run: |
        echo "✅ Infrastructure deployment completed successfully"
        echo "Backend App URL: ${{ steps.outputs.outputs.BACKEND_URL }}"
        echo "Frontend App URL: ${{ steps.outputs.outputs.FRONTEND_URL }}"

  post-deployment-setup:
    needs: validate-and-deploy
    runs-on: ubuntu-latest
    steps:
    - name: Verify resources
      run: |
        echo "Verifying deployed resources..."
        az containerapp show \
          --name helpsavta-production-backend \
          --resource-group ${{ env.AZURE_RESOURCE_GROUP }} \
          --query "properties.provisioningState" \
          --output tsv
        
        echo "✅ Resources verified successfully"